# Generated by Django 3.0 on 2023-04-25 04:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=11)),
                ('profile', models.ImageField(upload_to='images/profile/')),
                ('role', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=500)),
                ('designation', models.CharField(choices=[('Web Developer', 'Web Developer'), ('Web Designer', 'Web Designer'), ('Graphic Designer', 'Graphic Designer'), ('Digital Marketing', 'Digital Marketing')], max_length=200)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logo', models.ImageField(upload_to='images')),
                ('vedio', models.FileField(null=True, upload_to='videos_uploaded')),
                ('text', models.CharField(max_length=2000)),
            ],
        ),
    ]
